Repository team-e-techeer/teame-docs, pull requests merged in 2022-03, with the labels that each got.

#2 chore : Add team member
  README.md
Labels: test

#8 docs : Add team member 장동현
  README.md
Labels: duplicate

#10 docs : Add member name
  README.md
Labels: documentation

#11 docs : Add member 김의빈
  README.md
Labels: documentation
